from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
import time
from logger import logger

# Настройки прокси (если нужен)
proxy = "http://127.0.0.1:12334"  # Замените на ваш прокси

# Настройки для браузера
options = webdriver.ChromeOptions()
options.add_argument('--headless')  # Фоновый режим (обязательно для сервера)
options.add_argument('--disable-gpu')
options.add_argument('--no-sandbox')
options.add_argument(f'--proxy-server={proxy}')  # Прокси (если нужен)

# Укажите путь к вашему ChromeDriver
service = Service('/usr/bin/chromedriver')
driver = webdriver.Chrome(service=service, options=options)

# Открываем YouTube
driver.get('https://www.youtube.com')

# Ждём, пока страница загрузится
time.sleep(5)

# Получаем куки
cookies = driver.get_cookies()

logger.info("Сохраняем куки в файл в формате Netscape")
with open('../cookies/cookies.txt', 'w') as file:
    file.write("# Netscape HTTP Cookie File\n")
    file.write("# This file is generated by yt-dlp. Do not edit.\n")
    for cookie in cookies:
        logger.debug("Получаем значения с использованием метода get() для избежания KeyError")
        domain = cookie.get('domain', '')
        # Убедимся, что домен начинается с точки
        if not domain.startswith('.'):
            domain = '.' + domain
        domain_specified = 'TRUE'  # Всегда TRUE для доменов, начинающихся с точки
        path = cookie.get('path', '/')
        secure = 'TRUE' if cookie.get('secure', False) else 'FALSE'
        expires = str(int(cookie.get('expiry', 0))) if 'expiry' in cookie else '0'
        name = cookie.get('name', '')
        value = cookie.get('value', '')

        logger.debug("Преобразуем куки в формат Netscape")
        file.write(
            f"{domain}\t{domain_specified}\t{path}\t{secure}\t{expires}\t{name}\t{value}\n"
        )

logger.info("Закрываем браузер")
driver.quit()

logger.info("Куки успешно сохранены в файл cookies.txt")